version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: