name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t my-node-app .

    - name: Save Docker Image
      run: docker save my-node-app -o my-node-app.tar

    - name: Copy Docker Image to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "my-node-app.tar"
        target: "/home/ubuntu"

    - name: SSH into EC2 & Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker load -i my-node-app.tar
          docker stop my-node-app || true
          docker rm my-node-app || true
          docker-compose -f /home/ubuntu/docker-compose.yml up -d